# Public IP of the EC2 instance
output "ec2_public_ip" {
  description = "Public IP address of the EC2 application server"
  value       = aws_instance.app.public_ip
}

# Endpoint of the RDS database
output "db_endpoint" {
  description = "RDS PostgreSQL database endpoint"
  value       = aws_db_instance.postgres.address
}

# Direct link to the CloudWatch dashboard in AWS Console
output "cloudwatch_dashboard_url" {
  description = "CloudWatch dashboard URL for monitoring EC2 and RDS metrics"
  value       = "https://${var.aws_region}.console.aws.amazon.com/cloudwatch/home?region=${var.aws_region}#dashboards:name=${aws_cloudwatch_dashboard.main.dashboard_name}"
}

# Static website URL served via S3
output "s3_website_url" {
  description = "Public S3 website URL for the frontend application"
  value       = "http://${aws_s3_bucket.frontend.bucket}.s3-website-${var.aws_region}.amazonaws.com"
}

# ARN of the IAM role assumed by GitHub Actions
output "github_actions_role_arn" {
  description = "IAM role ARN used by GitHub Actions for deployments"
  value       = aws_iam_role.github_actions.arn
}

# URL of the ECR repository for backend Docker images
output "ecr_repository_url" {
  description = "ECR repository URL for pushing and pulling backend images"
  value       = aws_ecr_repository.backend.repository_url
}

# S3 static website endpoint (alternative to s3_website_url)
output "s3_website_endpoint" {
  description = "S3 static website endpoint (auto-generated by AWS)"
  value       = aws_s3_bucket_website_configuration.frontend.website_endpoint
}

# Host DB endpoint (duplicate of db_endpoint for clarity)
output "db_host" {
  description = "Database host endpoint for PostgreSQL"
  value       = aws_db_instance.postgres.address
}
